version: "3.8"
services:
  
  # nginx:
  #   build:
  #       context: .
  #       dockerfile: ./docker/nginx/Dockerfile
  #   container_name: nginx_cvnestreact
  #   volumes:
  #       - ./docker/nginx/default-http.conf:/etc/nginx/conf.d/default-http.conf
  #   ports:
  #       - 8081:80
  #   restart: always
    
  caddy:
    image: caddy:latest
    container_name: caddy_cvnestreact
    restart: unless-stopped
    ports:
      - "449:443"
    volumes:
      - ./docker/caddy/cvnestreact.com+4.pem:/etc/cert/cvnestreact/cvnestreact.com+4.pem
      - ./docker/caddy/cvnestreact.com+4-key.pem:/etc/cert/cvnestreact/cvnestreact.com+4-key.pem
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - .:/srv
      - caddy_data:/data
      - caddy_config:/config

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: web_cvnestreact
    volumes:
      - .:/srv

  database:
    container_name: postgres_cvnestreact
    image: postgres
    restart: always
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    environment:
      POSTGRES_PASSWORD: cvnestreact
      POSTGRES_USER: cvnestreact
      POSTGRES_DB: cvnestreact
      
  pgadmin:
    container_name: pgadmin_cvnestreact
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5059:80"
    links:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    
volumes:
  caddy_data:
  caddy_config:
    